name: Django Format, Lint, and Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format-lint-and-check:
    name: Format, Lint, and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox black djlint isort

      - name: Format code
        run: |
          black university
          isort university
          djlint --reformat university

      - name: Run flake8
        run: tox -e flake8

      - name: Run black check
        run: tox -e black-template

      - name: Run djlint check
        run: tox -e djlint

      - name: Run isort check
        run: tox -e isort

      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Apply automatic formatting" && git push)

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Notify about changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          echo "Formatting changes were made. Please pull the latest changes."
